############################################################################
# Contest 2026 team 031 GT911 touchscreen probe
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = gt911_probe
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_031_GT911_PROBE)

MAINSRC = gt911_probe_main.c

include $(APPDIR)/Application.mk
