############################################################################
# Contest 2026 team 031 MIPI-CSI staged camera probe
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = csi_probe
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_031_CSI_PROBE)

MAINSRC = csi_probe_main.c

include $(APPDIR)/Application.mk
