/* Generated by scripts/generate_smart_home_lvgl_icons.py; do not edit. */
#include "smart_home_lvgl_png_icons.h"

#include <string.h>

typedef struct {
    const char *name;
    const lv_image_dsc_t *small;
    const lv_image_dsc_t *base;
    const lv_image_dsc_t *large;
} smart_home_png_icon_entry_t;

static const smart_home_png_icon_entry_t g_png_icons[] = {
    {"asset:MIJIA", NULL, &smart_home_icon_MIJIA_32, NULL},
    {"asset:air-conditioning-disabled", NULL, &smart_home_icon_air_conditioning_disabled_32, NULL},
    {"asset:air-conditioning", &smart_home_icon_air_conditioning_20, &smart_home_icon_air_conditioning_32, &smart_home_icon_air_conditioning_48},
    {"asset:air-purifier", NULL, &smart_home_icon_air_purifier_32, NULL},
    {"asset:bath", NULL, &smart_home_icon_bath_32, NULL},
    {"asset:battery-vertical-charging", NULL, &smart_home_icon_battery_vertical_charging_32, NULL},
    {"asset:bed-king-outline", NULL, &smart_home_icon_bed_king_outline_32, NULL},
    {"asset:bell", NULL, &smart_home_icon_bell_32, NULL},
    {"asset:blinds-open", NULL, &smart_home_icon_blinds_open_32, NULL},
    {"asset:blinds", NULL, &smart_home_icon_blinds_32, NULL},
    {"asset:boombox", NULL, &smart_home_icon_boombox_32, NULL},
    {"asset:brand-line", NULL, &smart_home_icon_brand_line_32, NULL},
    {"asset:bulb", &smart_home_icon_bulb_20, &smart_home_icon_bulb_32, NULL},
    {"asset:camera-off", &smart_home_icon_camera_off_20, &smart_home_icon_camera_off_32, NULL},
    {"asset:camera", &smart_home_icon_camera_20, &smart_home_icon_camera_32, &smart_home_icon_camera_48},
    {"asset:cancel", NULL, &smart_home_icon_cancel_32, NULL},
    {"asset:chevron-right", NULL, &smart_home_icon_chevron_right_32, NULL},
    {"asset:cloud-cog", NULL, &smart_home_icon_cloud_cog_32, NULL},
    {"asset:cloud-rain", &smart_home_icon_cloud_rain_20, &smart_home_icon_cloud_rain_32, &smart_home_icon_cloud_rain_48},
    {"asset:cloud", NULL, &smart_home_icon_cloud_32, NULL},
    {"asset:corner-up-left", NULL, &smart_home_icon_corner_up_left_32, NULL},
    {"asset:device-computer-camera-off", NULL, &smart_home_icon_device_computer_camera_off_32, NULL},
    {"asset:device-computer-camera", NULL, &smart_home_icon_device_computer_camera_32, NULL},
    {"asset:devices", &smart_home_icon_devices_20, &smart_home_icon_devices_32, NULL},
    {"asset:door", NULL, &smart_home_icon_door_32, NULL},
    {"asset:dots", &smart_home_icon_dots_20, &smart_home_icon_dots_32, NULL},
    {"asset:fridge-off", NULL, &smart_home_icon_fridge_off_32, NULL},
    {"asset:fridge", NULL, &smart_home_icon_fridge_32, NULL},
    {"asset:home-shield", NULL, &smart_home_icon_home_shield_32, &smart_home_icon_home_shield_48},
    {"asset:home", &smart_home_icon_home_20, &smart_home_icon_home_32, &smart_home_icon_home_48},
    {"asset:lamp-2", NULL, &smart_home_icon_lamp_2_32, NULL},
    {"asset:lamp-off", NULL, &smart_home_icon_lamp_off_32, NULL},
    {"asset:lamp", NULL, &smart_home_icon_lamp_32, NULL},
    {"asset:link", NULL, &smart_home_icon_link_32, NULL},
    {"asset:loader", NULL, &smart_home_icon_loader_32, NULL},
    {"asset:lock-open", NULL, &smart_home_icon_lock_open_32, NULL},
    {"asset:lock", NULL, &smart_home_icon_lock_32, NULL},
    {"asset:message", NULL, &smart_home_icon_message_32, NULL},
    {"asset:microphone-off", &smart_home_icon_microphone_off_20, &smart_home_icon_microphone_off_32, NULL},
    {"asset:microphone", &smart_home_icon_microphone_20, &smart_home_icon_microphone_32, NULL},
    {"asset:minus", NULL, &smart_home_icon_minus_32, NULL},
    {"asset:moon", &smart_home_icon_moon_20, &smart_home_icon_moon_32, NULL},
    {"asset:music-circle-outline", NULL, &smart_home_icon_music_circle_outline_32, &smart_home_icon_music_circle_outline_48},
    {"asset:player-pause", NULL, &smart_home_icon_player_pause_32, NULL},
    {"asset:player-play", NULL, &smart_home_icon_player_play_32, NULL},
    {"asset:player-track-next", NULL, &smart_home_icon_player_track_next_32, NULL},
    {"asset:player-track-prev", NULL, &smart_home_icon_player_track_prev_32, NULL},
    {"asset:playlist", NULL, &smart_home_icon_playlist_32, NULL},
    {"asset:plug", NULL, &smart_home_icon_plug_32, NULL},
    {"asset:plus", NULL, &smart_home_icon_plus_32, NULL},
    {"asset:propeller", &smart_home_icon_propeller_20, &smart_home_icon_propeller_32, NULL},
    {"asset:robot-vacuum", NULL, &smart_home_icon_robot_vacuum_32, NULL},
    {"asset:robot", &smart_home_icon_robot_20, &smart_home_icon_robot_32, &smart_home_icon_robot_48},
    {"asset:run", NULL, &smart_home_icon_run_32, NULL},
    {"asset:sailboat", NULL, &smart_home_icon_sailboat_32, NULL},
    {"asset:settings", NULL, &smart_home_icon_settings_32, NULL},
    {"asset:shield", &smart_home_icon_shield_20, &smart_home_icon_shield_32, NULL},
    {"asset:sofa-single-outline", NULL, &smart_home_icon_sofa_single_outline_32, NULL},
    {"asset:sparkle-2", &smart_home_icon_sparkle_2_20, &smart_home_icon_sparkle_2_32, &smart_home_icon_sparkle_2_48},
    {"asset:stopwatch", NULL, &smart_home_icon_stopwatch_32, NULL},
    {"asset:sun", &smart_home_icon_sun_20, &smart_home_icon_sun_32, NULL},
    {"asset:television-classic", NULL, &smart_home_icon_television_classic_32, NULL},
    {"asset:temperature", &smart_home_icon_temperature_20, &smart_home_icon_temperature_32, NULL},
    {"asset:tool", NULL, &smart_home_icon_tool_32, NULL},
    {"asset:user", NULL, &smart_home_icon_user_32, NULL},
    {"asset:video-off", NULL, &smart_home_icon_video_off_32, NULL},
    {"asset:video", NULL, &smart_home_icon_video_32, NULL},
    {"asset:volume-2", NULL, &smart_home_icon_volume_2_32, NULL},
    {"asset:volume", NULL, &smart_home_icon_volume_32, NULL},
    {"asset:wash-machine", NULL, &smart_home_icon_wash_machine_32, NULL},
    {"asset:wifi-off", &smart_home_icon_wifi_off_20, &smart_home_icon_wifi_off_32, NULL},
    {"asset:wifi", &smart_home_icon_wifi_20, &smart_home_icon_wifi_32, NULL},
    {"asset:window", NULL, &smart_home_icon_window_32, NULL},
    {"asset:zzz", NULL, &smart_home_icon_zzz_32, NULL},
};

const lv_image_dsc_t *smart_home_lvgl_png_icon_get(const char *name, int requested_size)
{
    size_t i;

    if (!name) {
        return NULL;
    }
    for (i = 0; i < sizeof(g_png_icons) / sizeof(g_png_icons[0]); i++) {
        const smart_home_png_icon_entry_t *entry = &g_png_icons[i];

        if (strcmp(name, entry->name) != 0) {
            continue;
        }
        if (requested_size <= 24 && entry->small) {
            return entry->small;
        }
        if (requested_size > 32 && entry->large) {
            return entry->large;
        }
        return entry->base;
    }
    return NULL;
}
